// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djtbxzvhptxkbtdcnpup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqdGJ4enZocHR4a2J0ZGNucHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTYwMTIsImV4cCI6MjA1NzM3MjAxMn0.6jXMIYAfQLpvswZDfZu-Uzc6R-8vw7NjcMjOdRlDe-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);